# Permalinks

defaults:
  - 
    scope:
    path: ""
    type: "posts"
    values:
    permalink: 'archive/:title'
    
permalink:           pretty

# Setup
title:               Josh Nelson
tagline:             This is my tagline
url:                 http://joshcnelson.github.io/
baseurl:             ""


# Structure
pages_list:
  Introduction: '/introduction/'
  Projects: '/projects/'
  Resume: '/assets/resume.pdf'


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Josh Nelson
  url:               http://joshcnelson.github.io
  email:             joshcdnelson@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
